name: Build App

on:
push:

jobs:
build-windows:
runs-on: windows-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Install Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install Dependencies
    run: |
      pip install pillow pyinstaller

  - name: Build EXE
    run: |
      pyinstaller -w --noupx --clean --icon=app.ico --add-data "zy;zy" main.py

  - name: Upload Windows Build
    uses: actions/upload-artifact@v4
    with:
      name: windows-build
      path: dist/*

build-macos:
runs-on: macos-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Install Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install Dependencies
    run: |
      pip install pillow pyinstaller

  - name: Build APP
    run: |
      pyinstaller -w --clean --icon=app.icns --add-data "zy:zy" main.py

  - name: Upload Mac Build
    uses: actions/upload-artifact@v4
    with:
      name: mac-build
      path: dist/*
